CREATE DATABASE IF NOT EXISTS app_links;

USE app_links;

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users(
    id INT UNSIGNED NOT NULL,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);

ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE users
    MODIFY id  INT UNSIGNED NOT NULL AUTO_INCREMENT;

-- LINKS TABLES
CREATE TABLE IF NOT EXISTS links(
    id INT UNSIGNED NOT NULL,
    title VARCHAR(150) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT,
    user_id INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);